### ISSUE TITLE
Parse bugs

### ISSUE THREAD

**Issue by anylayer** [globocom/m3u8#358] opened 2024-03-05 02:52 UTC
https://m3u.haiwaikan.com/xm3u8/fff177dd1a7711a5b9647cb879c612b5832453bee2ab044c40504e42fded5e429921f11e97d0da21.m3u8

The first frame ts parsing failed and was ignored 

Version: 4.0.0

**Comment by mauricioabreu** [comment] 2024-05-10 12:35
@anylayer can you reproduce the bug using the version from master branch?
I tried it locally using the latest commit and it worked.

```
>>> m3u8.load("test.m3u8")
<m3u8.model.M3U8 object at 0x100e57cd0>
```

**Comment by anylayer** [comment] 2024-05-11 08:40
> https://m3u.haiwaikan.com/xm3u8/fff177dd1a7711a5b9647cb879c612b5832453bee2ab044c40504e42fded5e429921f11e97d0da21.m3u8
It seems not to be working
 version： 4.1.0

![image](https://github.com/globocom/m3u8/assets/46556817/0c59ccda-8440-4c80-b009-e6ef21a28015)
![image](https://github.com/globocom/m3u8/assets/46556817/2aded7c0-6228-4084-82da-00577fcf3af0)

**Comment by anylayer** [comment] 2024-05-11 08:41
> > https://m3u.haiwaikan.com/xm3u8/fff177dd1a7711a5b9647cb879c612b5832453bee2ab044c40504e42fded5e429921f11e97d0da21.m3u8
> > It seems not to be working
> > version： 4.1.0
> 
> ![image](https://private-user-images.githubusercontent.com/46556817/329767051-0c59ccda-8440-4c80-b009-e6ef21a28015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTcxMzIsIm5iZiI6MTcxNTQxNjgzMiwicGF0aCI6Ii80NjU1NjgxNy8zMjk3NjcwNTEtMGM1OWNjZGEtODQ0MC00YzgwLWIwMDktZTZlZjIxYTI4MDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA4NDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjY2E4ZWZiZDJjNzljYTFiNzI1OWI3MDVlZDhmYjE4NzFhMTVhOWRmZDcwMmI4MDVkZDQ5MjQzZDE2ZDU1N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yK8otE9a2fOy7fxUmNJvGAvBlB_EoubLdQS7xL6DR_E) ![image](https://private-user-images.githubusercontent.com/46556817/329767023-2aded7c0-6228-4084-82da-00577fcf3af0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTcxMzIsIm5iZiI6MTcxNTQxNjgzMiwicGF0aCI6Ii80NjU1NjgxNy8zMjk3NjcwMjMtMmFkZWQ3YzAtNjIyOC00MDg0LTgyZGEtMDA1NzdmY2YzYWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA4NDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZTk3NDUzODczMzY1YTk3NTkwY2M4NDE4NTQ2YjQ3YWNlYmYwYTQ4ZTI3MzMzMzkwZjgyYjk0YWM3NTUwZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FhwXyVeB-qTuoHVN2-8PVAP6O_MSqhhK94Zig7w9c-0)

The first ts file of this m3u8 doesn't seem to have been parsed.

**Comment by mauricioabreu** [comment] 2024-05-11 12:14
Thank you for the info!

**Comment by mauricioabreu** [comment] 2024-05-11 12:18
The problem is your playlist.

This is the beginning of your playlist:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:19
https://cdn.iz8qkg.com/fvod/fa0c5b4bbc45b8be40444db98f559c5ac7c7f0eb58e4b4ee1e6e28dd3568af5facf6b6fc65342a15fe97b1b115ba2e365534c7f60de7ec6d689572d763b07fc94b06a343b93d62c2921c07e8bfad678982f74bbb85bcca4b.ts
```

As you can see, the first segment is malformed because it is missing `#EXTINF` tag.

Closing since it is not a m3u8 bug. Reopen if needed.

**Closed by mauricioabreu** 2024-05-11 12:18 UTC

**Comment by leandromoreira** [comment] 2024-05-11 14:24
@davigsousa is working on a better error handling, that would provide better dev exp :) 🤞 

cc @mauricioabreu @anylayer

**Comment by leandromoreira** [comment] 2024-05-11 14:24
https://github.com/globocom/m3u8/pull/341
