### ISSUE TITLE
Having Trouble With Putting A M3U Stream In A M3U8 Link

### ISSUE THREAD

**Issue by InsolenceWillow** [globocom/m3u8#350] opened 2023-12-11 23:42 UTC
So here's what I got so far, although it doesn't work!
`#EXTM3U`
`#EXT-X-VERSION:3`
`#EXT-X-STREAM-INF:CODECS="avc1.4d0029,mp4a.40.2",RESOLUTION=1920x1080`
`http://mains.services/live/wickeduk/asdfasdfasdf3/87c5bc26-8724-439a-a84f-7ccf15fcb994.m3u`

**Comment by mauricioabreu** [comment] 2024-05-10 12:54
Hello, @InsolenceWillow 
What are you trying to do exactly?
What was the error caused by the code?

**Comment by mauricioabreu** [comment] 2024-05-10 23:47
Your playlist is missing `BANDWIDTH`. It is a mandatory attribute for every `EXT-X-STREAM-INF` tag.

I'm closing the issue. Reopen if needed.

**Closed by mauricioabreu** 2024-05-10 23:47 UTC
